#CI项目
name: ipq60xx-libWrt

#CI计划
on:
  # 手动执行
  workflow_dispatch:
  # 默认为utc时间，北京时间需要减去8
  schedule:
    - cron: 0 13 1/7 * *

#CI权限
permissions: write-all

#CI任务
jobs:
  config:
    name: ${{matrix.TARGET}}
    strategy:
      fail-fast: false
      #max-parallel: 3
      matrix:
        include:
          - TARGET: ipq60xx-libWrt-nowifi
            CONFIG_FILE: nowifi.config


    #调用公用编译核心WRT-CORE.yml
    uses: ./.github/workflows/core.yml
    with:
      #编译平台
      TARGET: ${{matrix.TARGET}}
      #源码
      REPO_SOURCE: LibWrt
      #源码地址
      REPO_URL: https://github.com/zhoufla/openwrt-6.x-breeze
      #源码分支
      REPO_BRANCH: openwrt-24.10
      #软件源
      FEEDS_CONF: feeds.conf.default
      #配置文件
      CONFIG_FILE: ./config/libWrt/${{matrix.CONFIG_FILE}}     

